### ISSUE TITLE
Compressing into .sar

### ISSUE THREAD

**Issue by malulleybovo** [HybridEidolon/saredit#1]
I see you have a nice method to decompress .sar files and load their data into the application. I have a symbol art editor available online (i.e.: a much improved version from the in game one available [here](https://malulleybovo.github.io/SymbolArtEditorOnline/)) but it still lacks support for .sar (it uses a dedicated xaml format right now) so I am really interested in your method. Do you happen to understand the three extra color variables parsed (x, y, z)? I guess they are related to color correction, but I do not know how they interpolate the raw RGB values.

**Comment by HybridEidolon** [comment]
I resumed working on this and didn't realize you had already built and completed something much more robust... oh well, lol @malulleybovo 

Encoding the .sar would have been implemented by a Rust wasm module built with wasm-pack, but I suppose there's no point to continue working on this if you've already completed everything.

**Comment by dosentmatter** [comment]
I think it can still be useful to PRS compress by compiling https://github.com/HybridEidolon/rust-ages-prs with `wasm-pack` and then optionally convert to asm.js with [`wasm2js`](https://github.com/WebAssembly/binaryen/blob/master/src/wasm2js.h) if support for older browsers is required.

It seems to me that he [currently skips](https://github.com/malulleybovo/SymbolArtEditorOnline/blob/1274b39f03f0255a2c48d6e4c25839ce2f34f145/js/sarloader.js#L44-L51) the optional PRS compression and 0x95 XOR that you mentioned in your [gist](https://gist.github.com/HybridEidolon/bc35fc03579c95550d0e6df824eede42). If you use his editor, you can see that loading then saving a file with no edits will increase file size since there is no compression.

I am curious how you were able to reverse engineer the `.sar` format in your [gist](https://gist.github.com/HybridEidolon/bc35fc03579c95550d0e6df824eede42)?

**Comment by HybridEidolon** [comment]
A Japanese hacker sent me some documentation a few years ago, and I was working on my own docs concurrently at that time. The parser in this repo is complete though.

The plan was to use ages-prs in a wasm context. Some PSO1 devs are using it for a web-based quest editor and it works great. I simply haven't had the time to work on this much and have been working on other things.
